#!/bin/bash
# Insight.app launcher — installed as Contents/MacOS/Insight by build_app.sh.
# __REPO_ROOT__, __PYTHON_BIN__, and __SITE_PACKAGES__ are baked in at build time.

set -u

REPO_ROOT="__REPO_ROOT__"
PYTHON_BIN="__PYTHON_BIN__"
SITE_PACKAGES="__SITE_PACKAGES__"
MAIN_SCRIPT="$REPO_ROOT/insight_desktop/app/main.py"
LOG_DIR="$REPO_ROOT/insight_desktop/logs"
LOG_FILE="$LOG_DIR/launcher.log"
TERMINAL_HELPER="$LOG_DIR/.insight-terminal-launch.sh"

mkdir -p "$LOG_DIR"

log() {
    printf '%s\n' "$@" >> "$LOG_FILE"
}

log "----- $(date) -----"

show_alert() {
    /usr/bin/osascript -e "display alert \"Insight\" message \"$1\" as critical" 2>/dev/null || true
}

repo_on_desktop() {
    case "$REPO_ROOT" in
        *"/Desktop"|*"/Desktop/"*) return 0 ;;
    esac
    return 1
}

# GUI-launched .app processes cannot read files under ~/Desktop (macOS privacy).
# Probe whether this launch context can actually open the main script.
can_launch_direct() {
    if repo_on_desktop; then
        log "Project is on Desktop — direct GUI launch not attempted"
        return 1
    fi
    if "$PYTHON_BIN" -c "open('$MAIN_SCRIPT').close()" >> "$LOG_FILE" 2>&1; then
        return 0
    fi
    log "Direct launch probe failed for $MAIN_SCRIPT"
    return 1
}

write_terminal_helper() {
    cat > "$TERMINAL_HELPER" <<EOF
#!/bin/bash
# Auto-generated by Insight.app — launches Insight with Terminal's folder access.
export PYTHONPATH=$(printf '%q' "$SITE_PACKAGES")
export PYTHONNOUSERSITE=1
export INSIGHT_REPO_ROOT=$(printf '%q' "$REPO_ROOT")
cd $(printf '%q' "$REPO_ROOT") || exit 1
exec $(printf '%q' "$PYTHON_BIN") $(printf '%q' "$MAIN_SCRIPT") >> $(printf '%q' "$LOG_FILE") 2>&1
EOF
    chmod +x "$TERMINAL_HELPER"
}

# Terminal already has access to ~/Desktop, so this is the reliable path when
# the project lives there. A Terminal tab stays open while Insight runs.
launch_via_terminal() {
    log "Launching via Terminal at $TERMINAL_HELPER"
    write_terminal_helper

    local escaped_helper
    escaped_helper=$(printf '%s' "$TERMINAL_HELPER" | sed "s/'/'\\\\''/g")

    if /usr/bin/osascript \
        -e 'tell application "Terminal" to activate' \
        -e "tell application \"Terminal\" to do script \"bash '${escaped_helper}'\""
    then
        log "Terminal launch script submitted"
        # Insight loads for several seconds before the main window appears.
        ( sleep 6
          /usr/bin/osascript <<'APPLESCRIPT' 2>/dev/null || true
tell application "System Events"
    repeat with proc in (every process whose name is "Python")
        set frontmost of proc to true
        exit repeat
    end repeat
end tell
APPLESCRIPT
        ) &
        return 0
    fi

    log "ERROR: AppleScript Terminal launch failed"
    show_alert "Insight could not start.\\n\\nOpen Terminal and run:\\nbash insight_desktop/packaging/build_app.sh\\n\\nOr move the project off Desktop to ~/Projects and rebuild."
    return 1
}

launch_direct() {
    export PYTHONPATH="$SITE_PACKAGES"
    export PYTHONNOUSERSITE=1
    export INSIGHT_REPO_ROOT="$REPO_ROOT"

    log "Direct launch: $PYTHON_BIN $MAIN_SCRIPT"

    if [ ! -x "$PYTHON_BIN" ]; then
        log "ERROR: Python not executable at $PYTHON_BIN"
        return 1
    fi
    if [ ! -f "$MAIN_SCRIPT" ]; then
        log "ERROR: main script missing at $MAIN_SCRIPT"
        return 1
    fi
    if [ ! -d "$SITE_PACKAGES" ]; then
        log "ERROR: site-packages missing at $SITE_PACKAGES"
        return 1
    fi

    cd "$REPO_ROOT" || return 1
    # Do not use exec here — if Python exits immediately we need to fall back.
    "$PYTHON_BIN" "$MAIN_SCRIPT" >> "$LOG_FILE" 2>&1
}

if [ ! -f "$MAIN_SCRIPT" ] && ! repo_on_desktop; then
    log "ERROR: main script missing at $MAIN_SCRIPT"
    show_alert "Insight project files not found at:\\n$REPO_ROOT\\n\\nRebuild the app after moving the project:\\nbash insight_desktop/packaging/build_app.sh"
    exit 1
fi

if can_launch_direct; then
    launch_direct
    status=$?
    if [ "$status" -eq 0 ]; then
        exit 0
    fi
    log "Direct launch exited with status $status — using Terminal fallback"
else
    log "Using Terminal launch path"
fi

launch_via_terminal >> "$LOG_FILE" 2>&1
exit $?
